### ISSUE TITLE
List possible enum values in the help for an Option

### ISSUE THREAD

**Issue by dodie** [rvesse/airline#102]
Hi!

I have a command, with an enum as an option:

```
public class MyCommand {
...
	@Option(name = {"--my-enum"}, description = "This is MyEnum. Possible values: EXAMPLE_A, EXAMPLE_B")
	MyEnum myEnum;
...
}
```

Is it possible to automatically include all possible values of the `enum` to the description instead of hard-coding them in the description?

I've tried to include them based on MyEnum.values(), but annotations can only consume [compile time constants](https://docs.oracle.com/javase/specs/jls/se7/html/jls-15.html#jls-15.28). Is there an airline annotation (or plans to have such feature) that makes this possible?

Cheers and thank you,
David

**Comment by rvesse** [comment]
The `@AllowedEnumValues` should do what you want, simply add this to the relevant option declaring the class of your enum e.g.

```
public class MyCommand {
...
	@Option(name = {"--my-enum"}, description = "This is MyEnum. Possible values: EXAMPLE_A, EXAMPLE_B")
        @AllowedEnumValues(MyEnum.class)
	MyEnum myEnum;
...
}
```

See http://rvesse.github.io/airline/guide/annotations/allowed-enum-values.html for the docs

This is a relatively new feature that was added as of the 2.7.0 release

**Comment by dodie** [comment]
Just what I needed, thanks, @rvesse !
