### ISSUE TITLE
Docs site is not very accessible for color-challenged readers

### ISSUE THREAD

**Issue by jshook** [rvesse/airline#121]
Syntax highlighting color makes examples really hard to read. The thin font with color `#00ccff` is really hard to read against a background of `#f9f9f9`. Maybe this is because I can't see all colors. People who can't distinguish red-green hues are not that uncommon. Can you look for a more accessible color palette for the docs site?
[edit: removed attached color swatch, it was incorrect, and github shows them inline!)

**Comment by rvesse** [comment]
Yes I can certainly look into it, been playing with the site viewed via https://www.toptal.com/designers/colorfilter and I can see that the colours don't show up well

**Comment by rvesse** [comment]
@jshook Sorry for not addressing this for a long time, I took a long hiatus from this project but I'm trying to get back into it again.

We use Jekyll with `rouge` as the syntax highlighter, this has a number of themes out of the box.  Is there any chance you could take a look at https://spsarolkar.github.io/rouge-theme-preview/ and try out the different themes and tell me which looks best for you?

I have switched over to `gruvbox.light` for now as I think that should improve things, but please let me know if there's a a better option available and I can make the switch over
