### ISSUE TITLE
Global options seems not to work

### ISSUE THREAD

**Issue by christian-raedel** [rvesse/airline#19]
Hi,

I have a ```GlobalOptions``` module and an abstract ```Command``` class where I inject this module into, like in the *GalaxyCommand* test unit. My first command inherits from this abstract ```Command``` and the printed help text shows my global options in a correct way. But when I execute ```myapp --globaloption``` all I get is the help text.
**Am I missing some parser setting? How is the correct way to get my command's ```run()``` method called?**

Regards,
Christian

**Comment by rvesse** [comment]
I am guessing you are defining a `Cli` as in the referenced unit test and that you have a `HelpCommand` set up that prints the help registered as your default command?

Note that use of global options don't change how the command to be run is determined.  The parser still expects to see a command name after any global options and if not selects the default command (assuming one is defined).

So running `myapp --globaloption` will simply cause your default command to be invoked whatever that happens to be.

If your default command is indeed just your help command and it doesn't do anything different if `--globaloption` is set then the behaviour described is as expected.

If this is not your setup and this doesn't explain the behaviour you see please can you provide some example code that demonstrates the exact issue you are having

**Comment by christian-raedel** [comment]
Thank you for your quick response. I have turned the return code of my ```Command``` into a flag and check this in my help command, which is the default command.
