### ISSUE TITLE
Invalid formatting and wrong example for the @Examples annotation

### ISSUE THREAD

**Issue by dodie** [rvesse/airline#83]
Hi!

First, thanks for maintaining this awesome library!
I was browsing the docs and found that the [docs](http://rvesse.github.io/airline/guide/annotations/examples.html) for the Examples annotation is mis-formatted and also contains an example using a different annotation.

Cheers,
David

**Comment by rvesse** [comment]
Thanks for spotting this, guess I got too copy-paste happy.  Fixes merged.
